config/routes.rb
ReyShop::Application.routes.draw do

  mount RailsAdmin::Engine => '/cms', :as => 'rails_admin'
  
  devise_for :admins

  devise_for :users

  namespace :user do
    root :to => "profile#index"
  end

  namespace :shop do
    get 'catalog'
    get 'sitemap'
    get 'show_parent_cat'
    get 'show_cat'
    get 'show_cat_s'
    get 'process_params'
    get 'index'
    get 'find'
    get 'find_s'
  end

  namespace :profile do
    get 'index'
    get 'show_order'
    get 'edit'
    get 'edit_addrs'
    get 'new_addrs'
    post 'update'
    post 'update_addrs'
    post 'new_addrs_add'
    post 'addrs_update'
  end
  
  resources :posts do
    resources :comments
    resources :tags
  end
  
  resources :products do
    resources :procomments, :proratings
  end

  resource :cart do
    post "add_product"
    post "remove_product"
    get "checkout"
    post "checkout_finish"
  end
  
  resources :xls
    
  resources :price
  
  resources :pages

  root :to => 'shop#index'

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  include ProcessParams
    
  def index
    @products = Product.all
  end
  
  def sitemap
    set_tab :sitemap
    @categories = Category.find_all_by_parent_id(0)
  end
    
  def show_cat 
    if (session[:user_url_processed] == "0" || !session[:user_url_processed] || params[:order_by] == nil || params[:desc_order_by] == nil)
      redirect_to process_params(request.url)
      return
    end
    session[:user_url_processed] = "0"
    set_tab :catalog
    @cat_ch = Array.new
    @cat = Category.find_by_id(params[:id])
    @cat_children = Category.find_by_parent_id(params[:id])
    @all = Category.all
    @all.each do |a|
      @cat_ch = Category.find_all_by_parent_id(a.id)
      @cat_ch.each do |ch|
        if @cat == ch
          @cat_parent = a
        end
      end
    end
    
    @cat = Category.find_by_id(params[:id])
    @cat_products = @cat.products.order(params[:order_by]+" "+params[:desc_order_by]).page(params[:page]).per(params[:per_page])
  end
  
  def show_parent_cat
    set_tab :catalog
    @cat = Category.find_by_id(params[:id])
    @cat_children = Category.find_all_by_parent_id(params[:id])
    @all = Category.all
    @all.each do |a|
      @cat_ch = Category.find_by_parent_id(a.id)
      if @cat == @cat_ch
        @cat_parent = a
      end
    end
    case @cat.id
    when 1
      set_tab :notebooks
    when 2
      set_tab :tablet
    when 3
      set_tab :computers
    when 4
      set_tab :phones
    when 5
      set_tab :players
    when 6
      set_tab :accessories
    end
  end
  
  def find
    set_tab :catalog
    if (session[:user_url_processed] == "0" || !session[:user_url_processed] || params[:order_by] == nil || params[:desc_order_by] == nil)
      redirect_to process_params(request.url)
      return
    end
    session[:user_url_processed] = "0"
    if params[:section] == nil
      @search_result, @counter = Category.new.search(params[:q])
      @alter_search = Kaminari.paginate_array(Product.new.search(params[:q], params[:desc_order_by], params[:order_by])).page(params[:page]).per(params[:per_page])
    else
      @search_result = Array.new
      @counter = Array.new
      @alter_search = Kaminari.paginate_array(Product.new.search_by_section(params[:section], params[:q], params[:desc_order_by], params[:order_by])).page(params[:page]).per(params[:per_page])
    end  
  end
  
  def catalog
    set_tab :catalog
  end
  
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/_catalog_breadcrumb.html.erb
<div class="breadcrumb">
	<span class="grey_cat"><%= link_to 'Главная страница', shop_index_path %></span>
	<span class="active_cat"><%= image_tag("active_arr.png") %><%= link_to 'Каталог', shop_catalog_path %></span>
</div>

app/views/shop/_find_part.html.erb
<table class="sort_table">
<tr>
<td><span>Вид:</span></td>
<td><%= link_to image_tag("table_active.png"), shop_find_path(:q => params[:q], :view => 'table')%></td>
<td><%= link_to image_tag("list_active.png"), shop_find_path(:q => params[:q], :view => 'list')%></td>
<td><span>Сортировка:</span></td>
<%if params[:order_by] == 'price'%>
	<%if params[:desc_order_by] == 'DESC'%>
		<td><span style = "grey_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'ASC')%></span><span style = "active_cat"><%= link_to "по цене", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'ASC')%><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'ASC')%></span></td>
	<%else%>
		<td><span style = "active_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'DESC')%><%= link_to "по цене", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'DESC')%></span><span style = "grey_cat"><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'price', :desc_order_by => 'DESC')%></span></td>
	<%end%>
	<td style = "grey_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'name')%><%= link_to "по имени", shop_find_path(:q => params[:q], :order_by => 'name')%><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'name')%></td>
<%else%>
	<td style = "grey_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'price')%><%= link_to "по цене", shop_find_path(:q => params[:q], :order_by => 'price')%><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'price')%></td>
	<%if params[:desc_order_by] == 'DESC'%>
		<td><span style = "grey_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'ASC')%></span><span style = "active_cat"><%= link_to "по имени", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'ASC')%><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'ASC')%></span></td>
	<%else%>
		<td><span style = "active_cat"><%= link_to "В", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'DESC')%><%= link_to "по имени", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'DESC')%></span><span style = "grey_cat"><%= link_to "Н", shop_find_path(:q => params[:q], :order_by => 'name', :desc_order_by => 'DESC')%></span></td>
	<%end%>
<%end%>
<td><span>Показывать по:</span></td>
<td>
<select>
<option value="<%= shop_find_path(:q => params[:q], :per_page => '5')%>">5</option>
<option value="<%= shop_find_path(:q => params[:q], :per_page => '10')%>">10</option>
<option value="<%= shop_find_path(:q => params[:q], :per_page => '25')%>">25</option>
<option value="<%= shop_find_path(:q => params[:q], :per_page => '50')%>">50</option>
</select></td>
</tr>
</table>

app/views/shop/_show_cat_part.html.erb
<table class="sort_table">
<tr>
<td><span>Вид:</span></td>
<td><%= link_to image_tag("table_active.png"), shop_show_cat_path(:id => @cat.id, :view => 'table')%></td>
<td><%= link_to image_tag("list_active.png"), shop_show_cat_path(:id => @cat.id, :view => 'list')%></td>
<td><span>Сортировка:</span></td>
<%if params[:order_by] == 'price'%>
	<%if params[:desc_order_by] == 'DESC'%>
		<td><span style = "grey_cat"><%= link_to image_tag("grey_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'ASC')%></span><span style = "active_cat"><%= link_to "по цене", shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'ASC')%><%= link_to image_tag("active_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'ASC')%></span></td>
	<%else%>
		<td><span style = "active_cat"><%= link_to image_tag("active_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'DESC')%><%= link_to "по цене", shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'DESC')%></span><span style = "grey_cat"><%= link_to image_tag("grey_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price', :desc_order_by => 'DESC')%></span></td>
	<%end%>
	<td style = "grey_cat"><%= link_to image_tag("grey_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name')%><%= link_to "по имени", shop_show_cat_path(:id => @cat.id, :order_by => 'name')%><%= link_to image_tag("grey_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name')%></td>
<%else%>
	<td style = "grey_cat"><%= link_to image_tag("grey_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price')%><%= link_to "по цене", shop_show_cat_path(:id => @cat.id, :order_by => 'price')%><%= link_to image_tag("grey_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'price')%></td>
	<%if params[:desc_order_by] == 'DESC'%>
		<td><span style = "grey_cat"><%= link_to image_tag("grey_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'ASC')%></span><span style = "active_cat"><%= link_to "по имени", shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'ASC')%><%= link_to image_tag("active_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'ASC')%></span></td>
	<%else%>
		<td><span style = "active_cat"><%= link_to image_tag("active_up.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'DESC')%><%= link_to "по имени", shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'DESC')%></span><span style = "grey_cat"><%= link_to image_tag("grey_down.png"), shop_show_cat_path(:id => @cat.id, :order_by => 'name', :desc_order_by => 'DESC')%></span></td>
	<%end%>
<%end%>
<td><span>Показывать по:</span></td>
<td>
<select>
<option value="<%= shop_show_cat_path(:id => @cat.id, :per_page => '5')%>">5</option>
<option value="<%= shop_show_cat_path(:id => @cat.id, :per_page => '10')%>">10</option>
<option value="<%= shop_show_cat_path(:id => @cat.id, :per_page => '25')%>">25</option>
<option value="<%= shop_show_cat_path(:id => @cat.id, :per_page => '50')%>">50</option>
</select></td>
</tr>
</table>

app/views/shop/_sitemap_breadcrumb.html.erb
<div class="breadcrumb">
	<span class="grey_cat"><%= link_to 'Главная страница', shop_index_path %></span>
	<span class="active_cat"><%= image_tag("active_arr.png") %><%= link_to 'Карта сайта', shop_sitemap_path %></span>
</div>

app/views/shop/catalog.html.erb
<%= render ('catalog_breadcrumb') %>
<div class="shadow">
<% main_categories.each do |cat| %>
	<% if cat.id != 47 %>
		<div class="category_show shadow first_bg ">
			<div class="category_name">
			<%=link_to cat.name+"("+cat.products.count.to_s+")", "#"%>
			</div>

			<%= image_tag "/images/category/"+cat.thumb_image %>
			<%=link_to shop_show_parent_cat_path(:id => cat.id) do%>
			<div class="second_bg shadow">	
      </div>
    <% end %>
		</div>
	<%end%>
<%end%>
<div class="empty_15"></div>
</div>

app/views/shop/find.html.erb
<%= render ('find_part') %>
Результаты поиска:<br />
<% if params[:view]=='list' %>
 Список:<br />
<% if @search_result != nil %>
	<% @search_result.each do |r| %>
		<%= link_to r.name, shop_find_path(:section => r.id, :q => params[:q]) %>
	<% end %>
	<% @counter.each do |ct| %>
		(<%= ct %>)
	<% end %>
<% end %>
<% if @alter_search != nil %>
	<% @alter_search.each do |ar| %>
		<p><%= link_to ar.name, ar %>, Цена:
		<%= ar.price %>
		<%=link_to "купить", {:controller => 'carts', :action => 'add_product', :item_id => ar.id}, :method => :post %></p>
	<% end %>
<% end %>
<%= paginate @alter_search %>
<% count = 0 %>
<% if @search_result[count] == nil and @alter_search[count] == nil %>
<%= 'Ничего не нашел, извини. Попробуй еще раз с другим поисковым запросом.'%>
<% end %>
<% else %>
 Таблица:<br />
<% if @search_result != nil %>
	<% @search_result.each do |r| %>
		<%= link_to r.name, shop_find_path(:section => r.id, :q => params[:q]) %>
	<% end %>
	<% @counter.each do |ct| %>
		(<%= ct %>)
	<% end %>
<% end %>
<% if @alter_search != nil %>
	<% @alter_search.each do |ar| %>
		<p><%= link_to ar.name, ar %>, Цена:
		<%= ar.price %>
		<%=link_to "купить", {:controller => 'carts', :action => 'add_product', :item_id => ar.id}, :method => :post %></p>
	<% end %>
<% end %>
<%= paginate @alter_search %>
<% count = 0 %>
<% if @search_result[count] == nil and @alter_search[count] == nil %>
<%= 'Ничего не нашел, извини. Попробуй еще раз с другим поисковым запросом.'%>
<% end %>
<% end %>

app/views/shop/index.html.erb
<h1>Главная страница</h1>
<%= link_to "Log out", destroy_user_session_path, method: "delete" %>

app/views/shop/show_cat.html.erb
<div class="shadow">
  <%= render ('show_cat_part') %>
  <%if params[:view]=='list'%>
    Список:<br />
    <div>
      <% @cat_products.each do |p| %>
        <div class="list_view  shadow">
          <div>
            <%= image_tag "/images/shop/"+p.thumb_image, :width => '215'%>
          </div>
          <div>
            <%= link_to p.name, p %><br />
            <%=p.price%><br />
            <%=link_to "купить", {:controller => 'carts', :action => 'add_product', :item_id => p.id}, :method => :post %><br />
            <%=raw p.short_desc%>
          </div>
        </div>
      <%end%>
    </div>
  <%else%>
    <div >
      <% @cat_products.each do |p| %>
        <div class="table_view product_show shadow">
          <div class="product_name">
            <%= link_to p.name, "#" %>
          </div>

          <div>
            <%= image_tag "/images/shop/"+p.thumb_image, class: "table_view_img"%>
          </div>
          <div class="product_price">
            <span class="word_price">цена: </span><span><%=p.price%>руб.</span>
          </div>
          <%= link_to add_product_cart_path(:item_id => p.id), :method => :post do %>
            <div class="buy_product">
              Купить
            </div>
          <% end %>
          <%= link_to p do %>
            <div class="second_product shadow">
            </div>
          <% end %>
        </div>
      <%end%>
    </div>
  <%end%>
  <div class="empty_15"></div>
  <%= paginate @cat_products %>
</div>

app/views/shop/show_parent_cat.html.erb
<div class="shadow">
  <div class="categoty_shop shadow">
    <% @cat_children.each do |cat_c| %>
      <div class="category_show shadow first_bg ">
        <div class="category_name">
          <%= link_to cat_c.name, '#'%>	
        </div>
        <%= image_tag "/images/category/"+cat_c.thumb_image%>
        <%= link_to :controller => 'shop', :action => 'show_cat', :id => cat_c.id do %>	
          <div class="second_bg shadow">	
          </div>
        <% end %>
      </div>

    <%end%>
    <div class="empty_15"></div>
  </div>
</div>	

app/views/shop/sitemap.html.erb
<%= render ('sitemap_breadcrumb') %>
<li><%= link_to get_page(1).name, get_page(1) %></li>
<li><%= link_to get_page(2).name, get_page(2) %></li>
<li><%= link_to get_page(3).name, price_index_path %></li>
<li><%= link_to get_page(4).name, get_page(4) %></li>
<li><%= link_to get_page(5).name, get_page(5) %></li>
<li><%= link_to get_page(7).name, get_page(7) %></li>
<% @categories.each do |c| %>
	<li><%= link_to c.name, shop_show_parent_cat_path(:id => c.id) %></li>
	<% children = Category.find_all_by_parent_id(c.id)%>
	<% children.each do |ch| %>
		<li><%= link_to ch.name, shop_show_cat_path(:id => ch.id) %></li>
	<% end %>
<% end %>
<li><%= link_to get_page(8).name, posts_path(:tag_id => '1') %></li>
<li><%= link_to get_page(9).name, posts_path %></li>
<li><%= link_to get_page(11).name, get_page(11) %></li>
<li><%= link_to get_page(12).name, profile_index_path %></li>