config/routes.rb
ReyShop::Application.routes.draw do

  mount RailsAdmin::Engine => '/cms', :as => 'rails_admin'
  
  devise_for :admins

  devise_for :users

  namespace :user do
    root :to => "profile#index"
  end

  namespace :shop do
    get 'catalog'
    get 'sitemap'
    get 'show_parent_cat'
    get 'show_cat'
    get 'show_cat_s'
    get 'process_params'
    get 'index'
    get 'find'
    get 'find_s'
  end

  namespace :profile do
    get 'index'
    get 'show_order'
    get 'edit'
    get 'edit_addrs'
    get 'new_addrs'
    post 'update'
    post 'update_addrs'
    post 'new_addrs_add'
    post 'addrs_update'
  end
  
  resources :posts do
    resources :comments
    resources :tags
  end
  
  resources :products do
    resources :procomments, :proratings
  end

  resource :cart do
    post "add_product"
    post "remove_product"
    get "checkout"
    post "checkout_finish"
  end
  
  resources :xls
    
  resources :price
  
  resources :pages

  root :to => 'shop#index'

end

app/views/shared/_footer.html.erb
<div id="footer">
    <div class="blue shadow">
    © 2011 Магазин Мега Пластинок  </div>
</div>

app/views/shared/_header.html.erb
<div class="header">
   
  <div class="top_blocks">
    <div class="left_top shadow">
      <div class="left_top_content">
        <div class="phone_number">
          <div class="phone_cod">
            (495) </br>
            (895)
          </div>
          <div class="phone">
            444-44-44
          </div>
        </div>
        <div class="work_time">
          -ежедневно с 10:00 до 21:00</br>
          -доставка по России и СНГ</br>
        </div>
      </div>
    </div>
    <div class="center_top shadow">
      <div class="logo_inform">
        <%= link_to "магазин мега пластинок", "/" %>
      </div>
    </div>
    <div class="right_top shadow">
      <div class="cart_pic">
        <%= link_to image_tag("cart_pic.png", :border=>0), edit_cart_path %>
      </div>
      <% @prod_count, @cart_total_price = count_cart %>
      <div class="quantity_of_goods">
        <%if @prod_count != 0%>
          товаров в корзине: <%=link_to " "+@prod_count.to_s, edit_cart_path%> 
        <%else%>
          <%=link_to "товаров в корзине: 0", edit_cart_path%>
        <%end%>
      </div>
      <div class="amount">
        <%if @prod_count != 0%>
          на сумму: <%= @cart_total_price %>р.
        <%else%>
          <%=link_to "корзина пуста", edit_cart_path%>
        <%end%>
      </div>
      <div class="to_order">
        <%if @prod_count != 0%>
          <%= link_to 'Оформить заказ', checkout_cart_path -%>
        <%end%>
      </div>
    </div>
  </div>
  <div class="navigation">
    <ul class="navigation_menu shadow menu_gradient">
    	<%= tabs_tag do |tab| %>
  			<%= tab.catalog	"Catalog", shop_catalog_path %>
  			<%= tab.profile	"Profile", profile_index_path %>
  			<li><%= form_tag("/shop/find", :method => "get", :class=>"search_form") do %>
        <%= text_field_tag(:q) %>
        <%= submit_tag "Search" , :class=>"hidden" %>
      <% end %></li>
		<% end %>
  </div>
  </ul>
  <ul id="top-nav">
  <% main_categories.each do |cat| %>
    <%if cat.id != 47%>
          <li>
          <% if curr_cat(params[:id]) != cat %>
          <%=link_to cat.name, shop_show_parent_cat_path(:id => cat.id), class: 'horiz'%>
          <% else %>
          <div class="current_top_nav"><%= cat.name %></div>
          <% end %>
          <% @cat_children = Category.find_all_by_parent_id(cat.id) %>
          <ul>
            <%@cat_children.each do |ct|%>
              <%ct_children = Category.find_all_by_parent_id(ct.id)%>
              <li class="vert">
              <%if ct_children.first%>
                <%=link_to ct.name, shop_show_parent_cat_path(:id => ct.id)%>
              <%else%>
                <%= link_to ct.name, shop_show_cat_path(:id => ct.id)%>
              <%end%>
              </li>
            <%end%>
          </ul>
          <div class='clear'></div>
          </li>
          <%end%>
        <% end %>
        </ul>

</div>