config/routes.rb
ReyShop::Application.routes.draw do

  mount RailsAdmin::Engine => '/cms', :as => 'rails_admin'
  
  devise_for :admins

  devise_for :users

  namespace :user do
    root :to => "profile#index"
  end

  namespace :shop do
    get 'catalog'
    get 'sitemap'
    get 'show_parent_cat'
    get 'show_cat'
    get 'show_cat_s'
    get 'process_params'
    get 'index'
    get 'find'
    get 'find_s'
  end

  namespace :profile do
    get 'index'
    get 'show_order'
    get 'edit'
    get 'edit_addrs'
    get 'new_addrs'
    post 'update'
    post 'update_addrs'
    post 'new_addrs_add'
    post 'addrs_update'
  end
  
  resources :posts do
    resources :comments
    resources :tags
  end
  
  resources :products do
    resources :procomments, :proratings
  end

  resource :cart do
    post "add_product"
    post "remove_product"
    get "checkout"
    post "checkout_finish"
  end
  
  resources :xls
    
  resources :price
  
  resources :pages

  root :to => 'shop#index'

end

app/controllers/carts_controller.rb
#encoding: utf-8
class CartsController < ApplicationController

  def edit

  end

  def add_product
    if user_signed_in?
      finded_order = Order.find_by_user_id_and_address_id(current_user.id,nil)
      if !finded_order
        cur_ord = Order.new
        cur_ord.user_id = current_user[:id]
        cur_ord.session_id = request.session_options[:id]
      else
        cur_ord = finded_order
        cur_ord.session_id = request.session_options[:id]
      end
    else
      finded_order = Order.find_by_session_id_and_address_id(request.session_options[:id],nil)
      if !finded_order
        cur_ord = Order.new
        cur_ord.session_id = request.session_options[:id]
      else
        cur_ord = finded_order
      end
    end

    finded_product = OrdersProduct.find_by_product_id_and_order_id(params[:item_id],cur_ord[:id])
    if !finded_product
      cur_ord_prod = cur_ord.orders_products.new
      cur_ord_prod.product_id = params[:item_id]
      prod = Product.find_by_id(params[:item_id])
      cur_ord_prod.price = prod.price
      cur_ord_prod.count = 1
      cur_ord.save
      cur_ord_prod.order_id = cur_ord.id
    else
      cur_ord_prod = finded_product
      cur_ord_prod.count += 1
      cur_ord.save
    end
    cur_ord_prod.save

    redirect_to '/cart/edit'
  end


  def update
    @quantity_arr = Array.new
    params[:cart].each do |cart|
      if (cart[1].to_i > 0 and cart[1].to_i < 50)
        prod = OrdersProduct.find_by_id(cart[0])
        prod["count"] = cart[1]
        prod.save
      end
    end
    respond_to do |format|
      render :text => "ok"
    end
  end

  def remove_product
    OrdersProduct.delete(params[:id])
    redirect_to :back
  end

  def checkout
    if !user_signed_in?
      deny_access
    end
    if @prod_count == 0
      flash[:notice] = "Пожалуйста, закажите что-нибудь, прежде чем приступать к оформлению"
      redirect_to :back
    end
  end

  def checkout_finish
    if (params[:name]=="" || params[:phone]=="" || params[:email]=="" || params[:address]=="" || params[:ship_method]=="")
      flash[:notice] = "Вы ввели не все необходимые данные"
      redirect_to :back
      return
    else
      if !user_signed_in?
        ord = Order.find_by_session_id_and_address_id(request.session_options[:id],nil)
        user = User.new
        @pass = random_password
        user.password = @pass
        user.password_confirmation = @pass
        entered_mail = params[:email]
        find_email = User.find_by_email(entered_mail)
        if (find_email)
          flash[:notice] = "Пользователь с таким e-mail адресом уже зарегистрирован"
          redirect_to :back
          return
        else
          user.email = params[:email]
        end
        flash[:notice] = "Ваш заказ обработан. Ваш пароль: #@pass"
      else
        ord = Order.find_by_user_id_and_address_id(current_user[:id],nil)
        user = current_user
        flash[:notice] = "Ваш заказ обработан."
        user.email = params[:email]
      end
      user.name = params[:name]
      user.phone = params[:phone]
      user.save

      ord.user_id = user.id

      if params[:address] == "Другой.."
        adr = Address.new
        adr.user_id = user.id
        adr.address = params[:new_address]
        adr.save
      else
        adr = Address.find_by_address(params[:address])
      end
      ord.address_id = adr.id

      shipm = ShipMethod.find_by_method(params[:ship_method])
      ord.ship_method_id = shipm.id

      ord.save

      #OrderMailer.new_user_and_new_order(user, @pass, ord).deliver
      redirect_to shop_index_path
    end
  end

  def random_password(size = 3)
    c = %w(b c d f g h j k l m n p qu r s t v w x z ch cr fr nd ng nk nt ph pr rd sh sl sp st th tr)
    v = %w(a e i o u y)
    f, r = true, ''
    (size * 2).times do
      r << (f ? c[rand * c.size] : v[rand * v.size])
      f = !f
    end
    r
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/checkout.html.erb
    <h1>Оформление заказа</h1>
	<%if user_signed_in?%>
	    <%= form_tag ('checkout_finish') do -%>
	
	    <p><%= label_tag 'Имя' %><br />
	    <%= text_field_tag 'name', current_user.name%></p>
	
	    <p><%= label_tag 'Телефон' %><br />
	    <%= text_field_tag 'phone', current_user.phone%></p>
	
	    <p><%= label_tag 'E-mail' %><br />
	    <%= text_field_tag 'email', current_user.email%></p>
	    <%addr = Address.find_all_by_user_id(current_user.id)%>
		
	    <%if addr.count > 1%>
	    	<%addr_array = Array.new%>
	    	<%addr.each do |ad|%>
	    		<%addr_array.push(ad.address)%>
	    	<%end%>
	    	<%addr_array.push("Другой..")%>
		    <p><%= label_tag 'Адрес доставки' %><br />
		    <%= select_tag(:address, options_for_select(addr_array)) %><p>	 
		    <p><%= label_tag 'Новый адрес доставки' %><br />
	    	<%= text_field_tag 'new_address', nil, :size => 75 %></p>	   
	    <%else%>	    
		    <p><%= label_tag 'Адрес доставки' %><br />
		    <%if addr.last != nil%>
		    	<%= text_field_tag 'new_address', addr.last.address, :size => 75 %></p>
		    <%else%>
		    	<%= text_field_tag 'new_address', nil, :size => 75 %></p>
		    <%end%>
		    <%= hidden_field_tag 'address', 'Другой..'%>
	    <%end%>

	    <p><%= label_tag 'Способ доставки' %><br/>
	    <%= radio_button_tag 'ship_method', 'C', :checked => true %>Доставка курьером<br />
	    <%= radio_button_tag 'ship_method', 'S' %>Самовывоз</p>
	
	    <p><%= submit_tag 'Подтвердить' %></p>
	    <% end -%>
	<%else%>
		<%= link_to 'Уже регистрировались?', new_user_session_path%>
	    <%= form_tag ('checkout_finish') do -%>
	
	    <p><%= label_tag 'Имя' %><br />
	    <%= text_field_tag 'name'%></p>
	
	    <p><%= label_tag 'Телефон' %><br />
	    <%= text_field_tag 'phone'%></p>
	
	    <p><%= label_tag 'E-mail' %><br />
	    <%= text_field_tag 'email'%></p>
	
	    <p><%= label_tag 'Адрес доставки' %><br />
	    <%= text_field_tag 'new_address', nil, :size => 75 %></p>
	    <%= hidden_field_tag 'address', 'Другой..'%>
	
	    <p><%= label_tag 'Способ доставки' %><br/>
	    <%= radio_button_tag 'ship_method', 'C', :checked => true %>Доставка курьером<br />
	    <%= radio_button_tag 'ship_method', 'S' %>Самовывоз</p>
	
	    <p><%= submit_tag 'Подтвердить' %></p>
	    <% end -%>
	<%end%>

app/views/carts/edit.html.erb
<div class="cart_page shadow">
<div class="word_cart">Корзина</div>
  
  <% if have_prods?  %>
    <% @total_price = 0 %>
    <%= form_for :cart, :url => (cart_path), :method => :put, :html => {:id => "cart-form"} do |f| %>

      <% @cart_order.orders_products.each do |prod| %>
        <div class="cart_product_block shadow">
          <div class="cart_product_pic">
            <%= link_to image_tag("/images/shop/"+prod.product.thumb_image, :border=>0), checkout_cart_path -%>
          </div>
          <div class="cart_product_name">
            <%= link_to prod.product.name, product_path(prod.product_id) -%>
          </div>
          <div class="cart_product_amount">
            <%= f.text_field prod.id, :value => prod.count, :size => 2, "price-value" => prod.price  -%>
          </div>
          <div class="cart_product_price">
            <%= pre_total = prod.price*prod.count %>руб
          </div>
          <div class="cart_product_delete">
            <%= link_to image_tag("delete.png", :border=>0), remove_product_cart_path(:id => prod.id), :method=>:post -%>
          </div>
          <%@total_price += pre_total%>
        </div>
      <% end %>

      <div class="score shadow">
        <span class="order_price">Стоимость заказа:</span><span class="amount_price"><%= @total_price %>руб<span>
          <% end %>
        </div>
        <div class="cart_buttons">
          <div class="continue_shopping buttons">
            <%= link_to 'Продолжить покупки', shop_index_path -%>
          </div>
          <div class="order_button buttons">
            <%= link_to 'Оформить заказ', checkout_cart_path -%>
          </div>
        </div>
      <%else%>
        <div class="notice_inform">Ваша корзина пуста</div>
      <%end%>
    </div>